# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.crystal.1.21.0.amd64.stamp: .container/base/deps/crystal/amd64.url.deps .container/base/deps/crystal/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/fetch.sh crystal
	touch $@

.container/base/deps/crystal/amd64.hash.deps: $(FETCH_PATH)/.crystal.1.21.0.amd64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=amd64 .makefile/container/scripts/update-hash.sh crystal

PREREQUISITES += .container/base/deps/crystal/amd64.hash.deps

$(FETCH_PATH)/.crystal.1.21.0.arm64.stamp: .container/base/deps/crystal/arm64.url.deps .container/base/deps/crystal/version.deps
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/fetch.sh crystal
	touch $@

.container/base/deps/crystal/arm64.hash.deps: $(FETCH_PATH)/.crystal.1.21.0.arm64.stamp
	M6E_DEPS_STAGE=base TARGETARCH=arm64 .makefile/container/scripts/update-hash.sh crystal

PREREQUISITES += .container/base/deps/crystal/arm64.hash.deps

